# Generated by Django 5.1.2 on 2024-10-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('university', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=100)),
                ('teaching_language', models.CharField(max_length=100)),
                ('languages', models.TextField(blank=True)),
                ('full_time_part_time', models.CharField(max_length=100)),
                ('program_duration', models.CharField(max_length=100)),
                ('beginning', models.CharField(max_length=100)),
                ('application_deadline', models.TextField()),
                ('tuition_fees', models.CharField(max_length=100)),
                ('combined_phd', models.CharField(max_length=100)),
                ('joint_degree', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('course_organisation', models.TextField(blank=True)),
                ('diploma_supplement', models.CharField(blank=True, max_length=100)),
                ('international_elements', models.TextField(blank=True)),
                ('german_language_courses', models.CharField(blank=True, max_length=100)),
                ('english_language_courses', models.CharField(blank=True, max_length=100)),
                ('semester_contribution', models.TextField(blank=True)),
                ('costs_of_living', models.TextField(blank=True)),
                ('funding_opportunities', models.TextField(blank=True)),
                ('academic_requirements', models.TextField()),
                ('language_requirements', models.TextField()),
                ('submit_application_to', models.TextField()),
                ('part_time_employment', models.TextField(blank=True)),
                ('accommodation', models.TextField(blank=True)),
                ('career_advisory_service', models.TextField(blank=True)),
                ('support_for_international_students', models.TextField(blank=True)),
                ('supervisor_student_ratio', models.CharField(blank=True, max_length=100)),
                ('about_university', models.TextField()),
            ],
        ),
    ]
