# Generated by Django 5.1.2 on 2024-10-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=100)),
                ('teaching_language', models.CharField(max_length=100)),
                ('languages', models.CharField(max_length=200)),
                ('programme_duration', models.CharField(max_length=100)),
                ('beginning', models.CharField(max_length=100)),
                ('application_deadline', models.CharField(max_length=100)),
                ('tuition_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('combined_masters_phd', models.BooleanField(default=False)),
                ('joint_double_degree', models.BooleanField(default=False)),
                ('description', models.TextField()),
            ],
        ),
    ]
