# Generated by Django 5.1.2 on 2024-10-16 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='universityprogram',
            options={'ordering': ['university', 'name']},
        ),
        migrations.AddField(
            model_name='universityprogram',
            name='application_end_date',
            field=models.DateField(blank=True, help_text='The final deadline for submitting the application', null=True),
        ),
        migrations.AddField(
            model_name='universityprogram',
            name='application_start_date',
            field=models.DateField(blank=True, help_text='The date when the application process opens', null=True),
        ),
        migrations.AddField(
            model_name='universityprogram',
            name='field',
            field=models.CharField(blank=True, choices=[('AI', 'Artificial Intelligence'), ('CS', 'Computer Science'), ('CYB', 'Cyber Security'), ('DS', 'Data Science')], help_text='Main field of study', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='universityprogram',
            name='gpa_score',
            field=models.FloatField(blank=True, help_text='Required GPA score (0-4 scale)', null=True),
        ),
        migrations.AddField(
            model_name='universityprogram',
            name='ielts_score',
            field=models.FloatField(blank=True, choices=[(5.5, '5.5'), (6.0, '6.0'), (6.5, '6.5'), (7.0, '7.0'), (7.5, '7.5'), (8.0, '8.0'), (8.5, '8.5'), (9.0, '9.0')], help_text='Required IELTS score for this program', null=True),
        ),
        migrations.AddField(
            model_name='universityprogram',
            name='is_checked',
            field=models.BooleanField(default=False, help_text='Have you reviewed this program?'),
        ),
        migrations.AddField(
            model_name='universityprogram',
            name='is_sufficient',
            field=models.BooleanField(default=True, help_text='Does this program meet your requirements?'),
        ),
        migrations.AddField(
            model_name='universityprogram',
            name='personal_note',
            field=models.TextField(blank=True, help_text='Your personal notes about this program'),
        ),
        migrations.CreateModel(
            name='ApplicationTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NS', 'Not Started'), ('IP', 'In Progress'), ('SU', 'Submitted'), ('UR', 'Under Review'), ('AC', 'Accepted'), ('RE', 'Rejected'), ('WL', 'Waitlisted')], default='NS', max_length=2)),
                ('application_submission_date', models.DateField(blank=True, null=True)),
                ('decision_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('priority', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0)),
                ('university_program', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.universityprogram')),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
    ]
