# Generated by Django 5.1.2 on 2024-10-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=100)),
                ('teaching_language', models.CharField(max_length=100)),
                ('other_languages', models.TextField(blank=True)),
                ('full_time_part_time', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('start_dates', models.CharField(max_length=100)),
                ('application_deadline', models.TextField()),
                ('tuition_fees', models.CharField(max_length=100)),
                ('combined_phd_program', models.CharField(max_length=100)),
                ('joint_degree', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('course_organisation', models.TextField()),
                ('diploma_supplement', models.CharField(max_length=100)),
                ('international_elements', models.TextField(blank=True)),
                ('german_language_courses', models.CharField(max_length=100)),
                ('english_language_courses', models.CharField(max_length=100)),
                ('semester_contribution', models.TextField(blank=True)),
                ('living_costs', models.TextField()),
                ('funding_opportunities', models.TextField(blank=True)),
                ('admission_requirements', models.TextField()),
                ('language_requirements', models.TextField()),
                ('application_process', models.TextField()),
                ('part_time_employment_info', models.TextField()),
                ('accommodation_info', models.TextField()),
                ('career_services', models.TextField(blank=True)),
                ('international_student_support', models.TextField()),
                ('supervisor_student_ratio', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='University',
        ),
    ]
