# Generated by Django 5.1.2 on 2024-10-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_universityprogram_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='universityprogram',
            name='link',
            field=models.URLField(blank=True, help_text='URL of the program', max_length=500),
        ),
    ]
