# Generated by Django 5.1.2 on 2024-10-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_universityprogram_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universityprogram',
            name='about_university',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprogram',
            name='academic_requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprogram',
            name='accommodation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprogram',
            name='application_deadline',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprogram',
            name='beginning',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='universityprogram',
            name='career_advisory_service',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprogram',
            name='combined_phd',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='universityprogram',
            name='costs_of_living',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprogram',
            name='course_organisation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprogram',
            name='degree',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='universityprogram',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprogram',
            name='diploma_supplement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='universityprogram',
            name='english_language_courses',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='universityprogram',
            name='full_time_part_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='universityprogram',
            name='funding_opportunities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprogram',
            name='german_language_courses',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='universityprogram',
            name='international_elements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprogram',
            name='joint_degree',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='universityprogram',
            name='language_requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprogram',
            name='languages',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprogram',
            name='link',
            field=models.URLField(blank=True, help_text='URL of the program', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='universityprogram',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='universityprogram',
            name='part_time_employment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprogram',
            name='personal_note',
            field=models.TextField(blank=True, help_text='Your personal notes about this program', null=True),
        ),
        migrations.AlterField(
            model_name='universityprogram',
            name='program_duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='universityprogram',
            name='semester_contribution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprogram',
            name='submit_application_to',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprogram',
            name='supervisor_student_ratio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='universityprogram',
            name='support_for_international_students',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprogram',
            name='teaching_language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='universityprogram',
            name='tuition_fees',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='universityprogram',
            name='university',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
