# Generated by Django 5.1.2 on 2024-10-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_universityprogram_about_university_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universityprogram',
            name='application_end_date',
        ),
        migrations.RemoveField(
            model_name='universityprogram',
            name='application_start_date',
        ),
        migrations.RemoveField(
            model_name='universityprogram',
            name='is_sufficient',
        ),
        migrations.AddField(
            model_name='universityprogram',
            name='status',
            field=models.CharField(choices=[('not_checked', 'Not Checked'), ('checked', 'Checked'), ('insufficient', 'Insufficient Requirements')], default='not_checked', help_text='Status of program review', max_length=15),
        ),
    ]
