# Generated by Django 5.1.2 on 2024-10-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_document_remove_applicationtracking_decision_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universityprogram',
            name='field',
        ),
        migrations.AddField(
            model_name='applicationtracking',
            name='field',
            field=models.CharField(blank=True, choices=[('AI', 'Artificial Intelligence'), ('CS', 'Computer Science'), ('CYB', 'Cyber Security'), ('DS', 'Data Science')], help_text='Main field of study', max_length=3, null=True),
        ),
    ]
