# Generated by Django 5.1.2 on 2024-11-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_remove_universityprogram_field_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="applicationtracking",
            options={},
        ),
        migrations.RemoveField(
            model_name="applicationtracking",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="applicationtracking",
            name="priority",
        ),
        migrations.RemoveField(
            model_name="applicationtracking",
            name="required_docs",
        ),
        migrations.RemoveField(
            model_name="applicationtracking",
            name="start_date",
        ),
        migrations.RemoveField(
            model_name="applicationtracking",
            name="university_program",
        ),
        migrations.AddField(
            model_name="applicationtracking",
            name="program",
            field=models.CharField(default="", max_length=255),
        ),
    ]
