# Generated by Django 5.1.2 on 2024-11-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_alter_applicationtracking_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationtracking",
            name="status",
            field=models.CharField(
                choices=[
                    ("NS", "Not Started"),
                    ("IP", "In Progress"),
                    ("AC", "Accepted"),
                    ("RE", "Rejected"),
                ],
                default="NS",
                max_length=2,
            ),
        ),
    ]
