# Generated by Django 5.1.2 on 2024-11-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_rename_program_applicationtracking_university_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationtracking",
            name="field",
            field=models.CharField(
                choices=[
                    ("AI", "Artificial Intelligence"),
                    ("CS", "Computer Science"),
                    ("CYB", "Cyber Security"),
                    ("DS", "Data Science"),
                    ("AUTO", "Autonomy"),
                ],
                help_text="Main field of study",
                max_length=30,
                null=True,
            ),
        ),
    ]
