# Generated by Django 5.1.2 on 2024-11-16 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_alter_applicationtracking_field"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Document",
        ),
    ]
