# Generated by Django 5.1.2 on 2024-11-16 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_delete_document"),
    ]

    operations = [
        migrations.CreateModel(
            name="University",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=100)),
                ("website", models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                "verbose_name_plural": "Universities",
            },
        ),
        migrations.AlterField(
            model_name="applicationtracking",
            name="university",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="applicationtracking",
            name="university_model",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="app.university",
            ),
        ),
    ]
