# Generated by Django 5.1.2 on 2024-11-16 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_university_alter_applicationtracking_university_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="university",
            old_name="website",
            new_name="url",
        ),
        migrations.RemoveField(
            model_name="university",
            name="country",
        ),
    ]
