# Generated by Django 5.1.2 on 2024-11-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_rename_university_model_applicationtracking_university"),
    ]

    operations = [
        migrations.AddField(
            model_name="university",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
