# Generated by Django 5.1.2 on 2024-11-16 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0018_university_notes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="university",
            old_name="url",
            new_name="portal_url",
        ),
    ]
