# Generated by Django 5.1.2 on 2024-11-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0019_rename_url_university_portal_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="university",
            options={},
        ),
        migrations.AddField(
            model_name="university",
            name="status",
            field=models.CharField(
                choices=[
                    ("fully_checked", "Fully Checked"),
                    ("partially_checked", "Partially Checked"),
                    ("not_checked", "Not Checked"),
                ],
                default="not_checked",
                max_length=20,
            ),
        ),
    ]
