# Generated by Django 5.1.2 on 2024-11-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0021_applicationtracking_program_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="university",
            name="status",
            field=models.CharField(
                choices=[
                    ("fully_checked", "Fully Checked"),
                    ("partially_checked", "Partially Checked"),
                    ("not_checked", "Not Checked"),
                    ("waiting_for_application", "Waiting for Application Time"),
                ],
                default="not_checked",
                max_length=30,
            ),
        ),
    ]
