# Generated by Django 5.1.2 on 2024-11-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0022_alter_university_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="university",
            name="portal_user_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
