# Generated by Django 5.1.2 on 2024-11-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0025_alter_applicationtracking_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationtracking",
            name="status",
            field=models.CharField(
                choices=[
                    ("NS", "Not Started"),
                    ("IP", "In Progress"),
                    ("RM", "Requirements Barely Met"),
                    ("AC", "Accepted"),
                    ("RE", "Rejected"),
                ],
                default="NS",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="university",
            name="status",
            field=models.CharField(
                choices=[
                    ("fully_checked", "Fully Checked"),
                    ("partially_checked", "Partially Checked"),
                    ("not_checked", "Not Checked"),
                    ("waiting_for_application", "Waiting for Application Time"),
                    ("UA", "Uni Assist Needed"),
                ],
                default="not_checked",
                max_length=30,
            ),
        ),
    ]
