# Generated by Django 5.1.2 on 2024-11-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0027_alter_applicationtracking_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationtracking",
            name="status",
            field=models.CharField(
                choices=[
                    ("NS", "Not Started"),
                    ("IP", "In Progress"),
                    ("RM", "Requirements Barely Met"),
                    ("AC", "Accepted"),
                    ("RE", "Rejected"),
                    ("SC", "Status Change"),
                ],
                default="NS",
                max_length=2,
            ),
        ),
    ]
