# Generated by Django 5.1.2 on 2024-11-19 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0028_alter_applicationtracking_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationtracking",
            name="field",
            field=models.CharField(
                choices=[
                    ("AI", "Artificial Intelligence"),
                    ("CS", "Computer Science"),
                    ("IS", "Information Systems"),
                    ("CYB", "Cyber Security"),
                    ("DS", "Data Science"),
                    ("AUTO", "Autonomy"),
                    ("Medical Imaging", "Medical Imaging"),
                    ("bioinformatics", "Bioinformatics"),
                    ("mathematics", "Mathematics"),
                ],
                help_text="Main field of study",
                max_length=30,
                null=True,
            ),
        ),
    ]
