# Generated by Django 5.1.2 on 2024-11-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "app",
            "0031_rename_application_submission_date_applicationtracking_start_date",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationtracking",
            name="is_open_admission",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="applicationtracking",
            name="is_uni_assist",
            field=models.BooleanField(default=False),
        ),
    ]
