# Generated by Django 5.1.2 on 2024-11-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0032_applicationtracking_is_open_admission_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationtracking",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
