# Generated by Django 5.1.2 on 2024-11-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0033_applicationtracking_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationtracking",
            name="status",
            field=models.CharField(
                choices=[
                    ("NS", "Not Started"),
                    ("IP", "In Progress"),
                    ("C1", "C1 Required"),
                    ("AC", "Accepted"),
                    ("RE", "Rejected"),
                ],
                default="NS",
                max_length=2,
            ),
        ),
    ]
