# Generated by Django 5.1.2 on 2024-11-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0034_alter_applicationtracking_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="applicationtracking",
            name="is_open_admission",
        ),
        migrations.RemoveField(
            model_name="applicationtracking",
            name="is_uni_assist",
        ),
        migrations.AddField(
            model_name="applicationtracking",
            name="application_portal",
            field=models.CharField(
                choices=[
                    ("NOT_PICKED", "Not Picked"),
                    ("PORTAL", "Portal"),
                    ("UNI_ASSIST", "Uni-Assist"),
                    ("OTHER", "Other"),
                ],
                default="NOT_PICKED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="applicationtracking",
            name="field",
            field=models.CharField(
                choices=[
                    ("AI", "Artificial Intelligence"),
                    ("CS", "Computer Science"),
                    ("IS", "Information Systems"),
                    ("CYB", "Cyber Security"),
                    ("DS", "Data Science"),
                    ("AUTO", "Autonomy"),
                    ("Medical Imaging", "Medical Imaging"),
                    ("bioinformatics", "Bioinformatics"),
                    ("mathematics", "Mathematics"),
                    ("EMBEDDED", "Embedded Systems"),
                    ("Cognitive", "Cognitive Science"),
                    ("computational", "Computational Linguistics"),
                ],
                help_text="Main field of study",
                max_length=30,
                null=True,
            ),
        ),
    ]
