# Generated by Django 5.1.2 on 2024-11-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0035_remove_applicationtracking_is_open_admission_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationtracking",
            name="status",
            field=models.CharField(
                choices=[
                    ("NS", "Not Started"),
                    ("WO", "Waiting for Opening"),
                    ("IP", "In Progress"),
                    ("AC", "Accepted"),
                ],
                default="NS",
                max_length=2,
            ),
        ),
    ]
